services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
  lobby.api:
    image: lobby.api
    build:
      context: .
      dockerfile: Lobby.API/Dockerfile

